name: release

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Release font files"
        required: true
        type: boolean

permissions:
  contents: write  # 允许写入内容
  issues: write    # 允许写入问题
  pull-requests: write  # 允许写入拉取请求

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip p7zip-full tar gzip bzip2 xz-utils tree unrar lz4 zstd python3

    - name: Download fonts
      run: |
        wget -q "https://github.com/ACT-02/PingFangUI-VF/releases/download/20.0d21e3/PingFangUI.wght.wdth.ttc"
        wget -q "https://github.com/yhchen/ttc2ttf/raw/refs/heads/master/ttc2ttf.py"
        md5sum *
        
    - name: ttc2ttf
      run: |
        ttc2ttf ttc2ttf.py PingFangUI.wght.wdth.ttc
        md5sum *

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 20.0d21e3  # 使用创建的标签
        name: font
        #body: TODO New Release.
        #body_path: CHANGELOG.txt
        draft: false
        prerelease: false
        files: |
          **
